groups:
    - development
    - design
recipes:
    mac_os_x:
        - osxdefaults::set_computer_name
attributes:
    osxdefaults:
        computername: Chris-Jones
    git:
        name: Chris Jones
        email: chris@union.co
    authorization:
        sudo:
            users:
                - Chris
