groups:
    - accounts
recipes:
    mac_os_x:
        - osxdefaults::set_computer_name
attributes:
    osxdefaults:
        computername: Christy-Dukes
    authorization:
        sudo:
            users:
                - Christy
            passwordless: true
            include_sudoers_d: true
