groups:
    - accounts
recipes:
    mac_os_x:
        - osxdefaults::set_computer_name
attributes:
    osxdefaults:
        computername: Claire-Outlaw
    authorization:
        sudo:
            users:
                - Claire
            passwordless: true
            include_sudoers_d: true
