groups:
    - accounts
recipes:
    mac_os_x:
        - osxdefaults::set_computer_name
attributes:
    osxdefaults:
        computername: Shannon-Parsley
    authorization:
        sudo:
            users:
                - Shannon
            passwordless: true
            include_sudoers_d: true
