groups:
    - accounts
recipes:
    mac_os_x:
        - osxdefaults::disable_natural_scrolling
        - osxdefaults::dock_automatically_hide_and_show_the_dock
        - osxdefaults::set_computer_name
attributes:
    osxdefaults:
        computername: Teresa-Cruz
