recipes:
    global:
        - applications::create_var_chef_cache
    mac_os_x:
        - homebrewalt::default
        - applications::launchrocket
        - applications::sublime_text_3
        - osxdefaults::disable_auto-correct
        - osxdefaults::enable_subpixel_font_rendering_on_non-apple_lcds
        - osxdefaults::finder_small_sidebar_icon_size
        - osxdefaults::finder_search_the_current_folder_by_default
        - osxdefaults::finder_display_full_path
        - osxdefaults::finder_use_column_view_in_all_finder_windows_by_default
        - osxdefaults::finder_allow_text_selection_in_quick_look
        - osxdefaults::finder_unhide_home
        - osxdefaults::finder_new_finder_windows_shows_homefolder
        - osxdefaults::automatically_illuminate_built-in_macbook_keyboard_in_low_light
        - osxdefaults::automatically_quit_printer_app_once_the_print_jobs_complete
        - osxdefaults::avoid_creating_ds_store_files_on_network_volumes
        - osxdefaults::save_screenshots_in_png_format
        - osxdefaults::save_screenshots_to_the_desktop
        - osxdefaults::tap_to_click
        - osxdefaults::dock_minimize_to_application
        - osxdefaults::dock_show_indicator_lights_for_open_applications_in_the_dock
        - osxdefaults::dock_enable_highlight_hover_effect_for_the_grid_view_of_a_stack
        - osxdefaults::dock_remove_the_animation_when_hiding_showing_the_dock
        - osxdefaults::dock_remove_the_auto-hiding_dock_delay
        - osxdefaults::menu_add_battery_percentage
        - osxdefaults::menu_show_clock_with_date
        - osxdefaults::mail_when_searching_do_not_include_trash
        - osxdefaults::mail_copy_email_addresses_instead_of_names_in_mail
        - osxdefaults::enable_assistive_devices
        - osxdefaults::enable_full_keyboard_access_for_all_controls
        - osxdefaults::increase_window_resize_speed_for_cocoa_applications
        - osxdefaults::speed_up_mission_control_animations
        - osxdefaults::set_terminal_profile
        - osxdefaults::add_a_context_menu_item_for_showing_the_web_inspector_in_web_views
        - osxdefaults::disable_press-and-hold_for_keys_in_favor_of_key_repeat
        - osxdefaults::set_a_blazingly_fast_keyboard_repeat_rate
        - osxdefaults::disable_disk_image_verification
        - osxdefaults::disable_gatekeeper
        - osxdefaults::disable_front_row
        - osxdefaults::disable_natural_scrolling
        - osxdefaults::disable_resume_system-wide
        - osxdefaults::do_not_show_dashboard_as_a_space
        - osxdefaults::prevent_time_machine_from_prompting_to_use_new_hard_drives_as_backup_volume
        - osxdefaults::finder_automatically_open_a_new_finder_window_when_a_volume_is_mounted
        - osxdefaults::finder_disable_the_warning_before_emptying_the_trash
        - osxdefaults::finder_disable_the_warning_when_changing_a_file_extension
        - osxdefaults::set_desktop_picture
#        - osxdefaults::set_computer_name
        - osxdefaults::add_note_to_loginscreen

attributes:
    osxdefaults:
        loginmessage: If found, please call (704) 335-5424
#        computername: name
        desktop_picture: http://union.co/assets/img/provision/bg.jpg
    dotfiles:
        project_dir: Projects
    workspace_directory: Projects
    homebrewalt:
        apps:
            - git
            - nodejs
        cask_apps:
            - google-chrome
            - google-drive
            - vlc
            - firefox
            - slack
            - dropbox
            - spotify
            - flux
            - slack
            - xtrafinder
            - adobe-creative-cloud
            - mou
            - invisionsync
            - google-hangouts
            - hyperdock
            - hyperswitch
            - caffeine
        cask_fonts:
            - inconsolata
