attributes:
    homebrewalt:
        cask_apps:
            - imageoptim
            - imagealpha
            - handbrake
            - slicy
            - adobe-creative-cloud
            - invisionsync
