recipes:
    global:
        - dotfiles::bash_it
        - dotfiles::inputrc
        - dotfiles::gitconfig
        - dotfiles::gem_setup
    mac_os_x:
        - nodejs::default
        - applications::ssh_config
        - applications::composer
        - applications::mysql
        - applications::php55
        - applications::sass
        - applications::rsync
        - applications::sublime_text_3
        - applications::launchrocket
attributes:
    mysql_root_password: "root"
    homebrewalt:
        apps:
            - git
            - git-extras
            - wget
            - git-flow
            - watch
            - rsync
            - bash-completion
        cask_apps:
            - sequel-pro
            - kaleidoscope
            - atom
            - github
            - hostbuddy
            - heroku-toolbelt
            - codebug
            - filezilla
            # - navicat-premium
            - rcenvironment
            - vagrant
            - virtualhostx
            - iterm2
    nodejs:
        apps:
            - bower
            - gulp
            - browser-sync
            - jshint
    gems:
        - sass
        - bundler
        - librarian-chef
    authorization:
        sudo:
            passwordless: true
            include_sudoers_d: true
